# pytorch_lightning==1.8.0rc0
seed_everything: true
trainer:
  max_epochs: 50
  accelerator: cpu
ckpt_path: null
model:
  class_path: spine_annotator.models.pl_modules.gnn_module.GNNModule
  init_args:
    onnx_export: false
    model:
      class_path: spine_annotator.models.classification.gnn.EncoderClassifier
      init_args:
        num_classes: 50
data:
  class_path: spine_annotator.datasets.patch_segmentation_dataset.PatchSegmentationDataModule
  init_args:
    data_dir: <path>
    batch_size: 16
    num_workers: 12
    subset_size: 5
