# pytorch_lightning==1.8.0rc0
seed_everything: true
trainer:
  max_epochs: 100
  min_epochs: 20
  accelerator: cpu
  callbacks:
    - class_path: lightning.pytorch.callbacks.early_stopping.EarlyStopping
      init_args:
        monitor: val_loss
        patience: 10
        mode: min
    # - class_path: spine_annotator.trainer.learning_rate_finder.FineTuneLearningRateFinder
    #   init_args:
    #     milestones: [0, 1, 3, 5, 10, 20, 50]
ckpt_path: null
model:
  class_path: spine_annotator.models.pl_modules.segmentation_module.SegmentationModule
  init_args:
    run_prefix: "SemUnet"
    experiment_name: "seg_Unet"
    num_classes: 3
    model:
      # class_path: monai.networks.nets.UNet
      # init_args:
      #   spatial_dims: 3
      #   in_channels: 1
      #   out_channels: 26
      #   channels: [64, 128, 128, 256, 512, 1024, 1024]
      #   strides: [2, 1, 2, 2, 2, 1]
      #   num_res_units: 2
      #   dropout: 0.5
      class_path: segmentation_models_pytorch.Unet
      init_args:
      #  encoder_name: "efficientnetb7"
         encoder_name: "resnet152"
      #   # encoder_name: "timm-resnest200e"
         in_channels: 3
      #   # classes: 48
      #   # classes: 26 # background (1) + C2...L5 (23) + S1 (1) + L6 (1) == 26 (L6 is rare)
         classes: 3
    loss:
      # class_path: torch.nn.CrossEntropyLoss
      #class_path: torch.nn.MSELoss
      class_path: segmentation_models_pytorch.losses.DiceLoss
      # class_path: segmentation_models_pytorch.losses.JaccardLoss
      init_args:
        mode: multiclass
        log_loss: true
        #classes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
        # classes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
        # classes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]
        classes: [1, 2]
    augmentation:
      class_path: spine_annotator.datasets.augmentation.ImageAugmentation
      init_args:
         cropping_type: "many"
         geometric_aug_type: "all"
         photometric_aug_type: "all"
    #num_classes: 26
    # num_classes: 48
data:
  class_path: spine_annotator.datasets.segmentation_dataset.SegmentationDataModule
  init_args:
    data_dir:
      - datasets/nako_splits/train_seg.csv
      - datasets/nako_splits/val_seg.csv
    batch_size: 8
    num_workers: 16
    target_shape: [18, 320, 896]
    crop_height_to_px: 896
    # gt_format:
    #   separation: instance
    #   order: y-sort
    #   include: wk

    slice_wise: true
    augment: false
    triple_same_slice: false
    add_adjacent_slices: true
    add_bs_wk_as_channels: false
